### ISSUE TITLE
config.yml and hikari.properties have mismatched values

### ISSUE THREAD

**Issue by Bobcat00** [AddstarMC/Prism-Bukkit#130]
The defaults in config.yml and hikari.properties have different values.  They should be changed to match, or if the default values in config.yml no longer apply, they should be removed from the code.

In particular, max-pool-connections (20) / maximumPoolSize (10) and min-idle-connections (5) / minimumIdle (10) don't match.  There may be others.

Prism 2.1.6-SNAPSHOT-118
MySQL 5.7.29
git-Spigot-6de3d4b-fc24934 (MC: 1.15.2)

The following were generated for the default files.

config.yml:
```
  mysql:
    hostname: 127.0.0.1
    username: root
    password: ''
    databaseName: minecraft
    prefix: prism_
    port: '3306'
    useNonStandardSql: true
    database:
      max-pool-connections: 20
      min-idle-connections: 5
      max-wait: 30000
      max-failures-before-wait: 5
      actions-per-insert-batch: 300
      force-write-queue-on-shutdown: true
```
hikari.properties:
```
#Prism Hikari Datasource Properties for advanced database Configuration
#Thu Mar 12 11:11:51 EDT 2020
allowPoolSuspension=false
poolName=prism
registerMbeans=false
maxLifetime=1800000
autoCommit=true
leakDetectionThreshold=0
maximumPoolSize=10
idleTimeout=600000
validationTimeout=5000
minimumIdle=10
isolateInternalQueries=false
initializationFailTimeout=1
readOnly=false
connectionTimeout=30000
```
