### ISSUE TITLE
pste.me references still show in config

### ISSUE THREAD

**Issue by viveleroi** [AddstarMC/Prism-Bukkit#159]
Prism 2.1.6 still has references to pste.me in the default configuration file:

```
  paste:
    enable: false
    username: Username on http://pste.me/#/signup
    api-key: API key from http://pste.me/#/account
```
